version: '3.9'

services:
  iot-backend-api-v1:
    image: iot-backend-api:17.11.24
    container_name: iot-backend-v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - '4000:4000'
    networks:
      - iot-network
    environment:
      PORT: ${PORT}
      SECRET_KEY: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

networks:
  iot-network:
    external: true